export {default as AcrylIcon} from './AcrylIcon';
export {default as EngravingIcon} from './EngravingIcon';
export {default as HammerIcon} from './HammerIcon';
export {default as OthersIcon} from './OthersIcon';
export {default as PaintIcon} from './PaintIcon';
export {default as PlasticIcon} from './PlasticIcon';
export {default as PrintIcon} from './PrintIcon';
export {default as PrintingIcon} from './PrintingIcon';
export {default as TreeIcon} from './TreeIcon';
